name: Push docs to UE4SS-RE/docs

on:
  push:
    branches:
      - Release
      - 3.XDev
      - TestNewDocs
    paths:
      - "docs/**"

jobs:
  push_to_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to main branch
        if: github.ref == 'refs/heads/Release'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_GITHUB_TOKEN }}
        with:
          source-directory: 'docs'
          destination-github-username: 'UE4SS-RE'
          destination-repository-name: 'docs'
          target-branch: main
          target-directory: 'src'
          
      - name: Upload to dev/src directory
        if: github.ref == 'refs/heads/3.XDev'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_GITHUB_TOKEN }}
        with:
          source-directory: 'docs'
          destination-github-username: 'UE4SS-RE'
          destination-repository-name: 'docs'
          target-branch: main
          target-directory: 'dev/src'
          
      - name: Test upload to dev/src directory 2
        if: github.ref == 'refs/heads/TestNewDocs'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_GITHUB_TOKEN }}
        with:
          source-directory: 'docs'
          destination-github-username: 'UE4SS-RE'
          destination-repository-name: 'docs'
          target-branch: main
          target-directory: 'dev/src'
